name: Generate CastFM APK
on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Initialize and Build APK
        # এখানে 'yes' কমান্ডটি সব অটোমেটিক উত্তর দিয়ে দেবে
        run: |
          yes | bubblewrap init --manifest=https://castfm.pages.dev/manifest.json --directory=./ --metaData=./twa-manifest.json
          yes | bubblewrap build --skip-signing

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CastFM-Release-APK
          path: ./*.apk
